contact_links:
  - name: GitHub Discussions
    url: https://github.com/Mrcomputer1/SmileyPlayerTrader/discussions
    about: Ask questions, submit ideas and talk about Smiley Player Trader here.
  - name: Discord
    url: https://discord.gg/SdM6f7U
    about: Ask questions and talk about Smiley Player Trader on Discord.
